services:
  bumblebee:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bumblebee
    environment:
      BUMBLEBEE_SERVICE_NAME: bumblebee
      BUMBLEBEE_ENV: local
      BUMBLEBEE_VERSION: dev
      BUMBLEBEE_HTTP_ADDR: :8080
      BUMBLEBEE_GRPC_ADDR: :9090
      BUMBLEBEE_DB_DSN: ${BUMBLEBEE_DOCKER_DB_DSN}
      BUMBLEBEE_KAFKA_BROKERS: kafka:29092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8080:8080"
      - "9090:9090"

  postgres:
    image: postgres:18-alpine
    container_name: bumblebee-postgres
    environment:
      POSTGRES_DB: ${BUMBLEBEE_POSTGRES_DB}
      POSTGRES_USER: ${BUMBLEBEE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BUMBLEBEE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnamilegacy/kafka:3.9.0
    container_name: bumblebee-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_KRAFT_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      ALLOW_PLAINTEXT_LISTENER: "yes"
