// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: api/content/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Title               string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slug                string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CurrentRevisionId   string                 `protobuf:"bytes,7,opt,name=current_revision_id,json=currentRevisionId,proto3" json:"current_revision_id,omitempty"`
	PublishedRevisionId string                 `protobuf:"bytes,8,opt,name=published_revision_id,json=publishedRevisionId,proto3" json:"published_revision_id,omitempty"`
	CreatedBy           string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy           string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ArchivedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	CurrentRevision     *ContentRevision       `protobuf:"bytes,15,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	Tags                []*Tag                 `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets              []*ContentAsset        `protobuf:"bytes,17,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContentItem) Reset() {
	*x = ContentItem{}
	mi := &file_api_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentItem) ProtoMessage() {}

func (x *ContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentItem.ProtoReflect.Descriptor instead.
func (*ContentItem) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ContentItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContentItem) GetCurrentRevisionId() string {
	if x != nil {
		return x.CurrentRevisionId
	}
	return ""
}

func (x *ContentItem) GetPublishedRevisionId() string {
	if x != nil {
		return x.PublishedRevisionId
	}
	return ""
}

func (x *ContentItem) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ContentItem) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ContentItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContentItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ContentItem) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *ContentItem) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *ContentItem) GetCurrentRevision() *ContentRevision {
	if x != nil {
		return x.CurrentRevision
	}
	return nil
}

func (x *ContentItem) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ContentItem) GetAssets() []*ContentAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type ContentRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentItemId string                 `protobuf:"bytes,2,opt,name=content_item_id,json=contentItemId,proto3" json:"content_item_id,omitempty"`
	Revision      int32                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SourceHash    string                 `protobuf:"bytes,6,opt,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRevision) Reset() {
	*x = ContentRevision{}
	mi := &file_api_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRevision) ProtoMessage() {}

func (x *ContentRevision) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRevision.ProtoReflect.Descriptor instead.
func (*ContentRevision) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *ContentRevision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentRevision) GetContentItemId() string {
	if x != nil {
		return x.ContentItemId
	}
	return ""
}

func (x *ContentRevision) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ContentRevision) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ContentRevision) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContentRevision) GetSourceHash() string {
	if x != nil {
		return x.SourceHash
	}
	return ""
}

func (x *ContentRevision) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContentRevision) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ContentRevision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_api_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ContentAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentItemId string                 `protobuf:"bytes,2,opt,name=content_item_id,json=contentItemId,proto3" json:"content_item_id,omitempty"`
	RevisionId    string                 `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,7,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentAsset) Reset() {
	*x = ContentAsset{}
	mi := &file_api_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentAsset) ProtoMessage() {}

func (x *ContentAsset) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentAsset.ProtoReflect.Descriptor instead.
func (*ContentAsset) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *ContentAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentAsset) GetContentItemId() string {
	if x != nil {
		return x.ContentItemId
	}
	return ""
}

func (x *ContentAsset) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *ContentAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ContentAsset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentAsset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentAsset) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ContentAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateContentAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentAsset) Reset() {
	*x = CreateContentAsset{}
	mi := &file_api_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentAsset) ProtoMessage() {}

func (x *CreateContentAsset) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentAsset.ProtoReflect.Descriptor instead.
func (*CreateContentAsset) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContentAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateContentAsset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateContentAsset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentAsset) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateContentItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets        []*CreateContentAsset  `protobuf:"bytes,11,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentItemRequest) Reset() {
	*x = CreateContentItemRequest{}
	mi := &file_api_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentItemRequest) ProtoMessage() {}

func (x *CreateContentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentItemRequest.ProtoReflect.Descriptor instead.
func (*CreateContentItemRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContentItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContentItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateContentItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentItemRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateContentItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateContentItemRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateContentItemRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateContentItemRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateContentItemRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateContentItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateContentItemRequest) GetAssets() []*CreateContentAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type CreateContentItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ContentItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentItemResponse) Reset() {
	*x = CreateContentItemResponse{}
	mi := &file_api_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentItemResponse) ProtoMessage() {}

func (x *CreateContentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentItemResponse.ProtoReflect.Descriptor instead.
func (*CreateContentItemResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{6}
}

func (x *CreateContentItemResponse) GetItem() *ContentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetContentItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentItemRequest) Reset() {
	*x = GetContentItemRequest{}
	mi := &file_api_content_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentItemRequest) ProtoMessage() {}

func (x *GetContentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentItemRequest.ProtoReflect.Descriptor instead.
func (*GetContentItemRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContentItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ContentItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentItemResponse) Reset() {
	*x = GetContentItemResponse{}
	mi := &file_api_content_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentItemResponse) ProtoMessage() {}

func (x *GetContentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentItemResponse.ProtoReflect.Descriptor instead.
func (*GetContentItemResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{8}
}

func (x *GetContentItemResponse) GetItem() *ContentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListContentItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentItemsRequest) Reset() {
	*x = ListContentItemsRequest{}
	mi := &file_api_content_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentItemsRequest) ProtoMessage() {}

func (x *ListContentItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentItemsRequest.ProtoReflect.Descriptor instead.
func (*ListContentItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{9}
}

type ListContentItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContentItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentItemsResponse) Reset() {
	*x = ListContentItemsResponse{}
	mi := &file_api_content_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentItemsResponse) ProtoMessage() {}

func (x *ListContentItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentItemsResponse.ProtoReflect.Descriptor instead.
func (*ListContentItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{10}
}

func (x *ListContentItemsResponse) GetItems() []*ContentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateContentItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentItemRequest) Reset() {
	*x = UpdateContentItemRequest{}
	mi := &file_api_content_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentItemRequest) ProtoMessage() {}

func (x *UpdateContentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentItemRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateContentItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateContentItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateContentItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateContentItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContentItemRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateContentItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateContentItemRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateContentItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ContentItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentItemResponse) Reset() {
	*x = UpdateContentItemResponse{}
	mi := &file_api_content_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentItemResponse) ProtoMessage() {}

func (x *UpdateContentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateContentItemResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateContentItemResponse) GetItem() *ContentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteContentItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentItemRequest) Reset() {
	*x = DeleteContentItemRequest{}
	mi := &file_api_content_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentItemRequest) ProtoMessage() {}

func (x *DeleteContentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentItemRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteContentItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteContentItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ContentItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentItemResponse) Reset() {
	*x = DeleteContentItemResponse{}
	mi := &file_api_content_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentItemResponse) ProtoMessage() {}

func (x *DeleteContentItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentItemResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteContentItemResponse) GetItem() *ContentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateContentRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentItemId string                 `protobuf:"bytes,1,opt,name=content_item_id,json=contentItemId,proto3" json:"content_item_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRevisionRequest) Reset() {
	*x = CreateContentRevisionRequest{}
	mi := &file_api_content_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRevisionRequest) ProtoMessage() {}

func (x *CreateContentRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRevisionRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRevisionRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{15}
}

func (x *CreateContentRevisionRequest) GetContentItemId() string {
	if x != nil {
		return x.ContentItemId
	}
	return ""
}

func (x *CreateContentRevisionRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateContentRevisionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateContentRevisionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateContentRevisionRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateContentRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *ContentRevision       `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRevisionResponse) Reset() {
	*x = CreateContentRevisionResponse{}
	mi := &file_api_content_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRevisionResponse) ProtoMessage() {}

func (x *CreateContentRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRevisionResponse.ProtoReflect.Descriptor instead.
func (*CreateContentRevisionResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{16}
}

func (x *CreateContentRevisionResponse) GetRevision() *ContentRevision {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ListContentRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentItemId string                 `protobuf:"bytes,1,opt,name=content_item_id,json=contentItemId,proto3" json:"content_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentRevisionsRequest) Reset() {
	*x = ListContentRevisionsRequest{}
	mi := &file_api_content_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentRevisionsRequest) ProtoMessage() {}

func (x *ListContentRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentRevisionsRequest.ProtoReflect.Descriptor instead.
func (*ListContentRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{17}
}

func (x *ListContentRevisionsRequest) GetContentItemId() string {
	if x != nil {
		return x.ContentItemId
	}
	return ""
}

type ListContentRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*ContentRevision     `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentRevisionsResponse) Reset() {
	*x = ListContentRevisionsResponse{}
	mi := &file_api_content_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentRevisionsResponse) ProtoMessage() {}

func (x *ListContentRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_content_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListContentRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_api_content_content_proto_rawDescGZIP(), []int{18}
}

func (x *ListContentRevisionsResponse) GetRevisions() []*ContentRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

var File_api_content_content_proto protoreflect.FileDescriptor

const file_api_content_content_proto_rawDesc = "" +
	"\n" +
	"\x19api/content/content.proto\x12\x11overmindv.content\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x05\n" +
	"\vContentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12.\n" +
	"\x13current_revision_id\x18\a \x01(\tR\x11currentRevisionId\x122\n" +
	"\x15published_revision_id\x18\b \x01(\tR\x13publishedRevisionId\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fpublished_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12;\n" +
	"\varchived_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x12M\n" +
	"\x10current_revision\x18\x0f \x01(\v2\".overmindv.content.ContentRevisionR\x0fcurrentRevision\x12*\n" +
	"\x04tags\x18\x10 \x03(\v2\x16.overmindv.content.TagR\x04tags\x127\n" +
	"\x06assets\x18\x11 \x03(\v2\x1f.overmindv.content.ContentAssetR\x06assets\"\xaa\x02\n" +
	"\x0fContentRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcontent_item_id\x18\x02 \x01(\tR\rcontentItemId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x05R\brevision\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_hash\x18\x06 \x01(\tR\n" +
	"sourceHash\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"x\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x02\n" +
	"\fContentAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcontent_item_id\x18\x02 \x01(\tR\rcontentItemId\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\tR\n" +
	"revisionId\x12\x19\n" +
	"\basset_id\x18\x04 \x01(\tR\aassetId\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\a \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"u\n" +
	"\x12CreateContentAsset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\xce\x02\n" +
	"\x18CreateContentItemRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12=\n" +
	"\x06assets\x18\v \x03(\v2%.overmindv.content.CreateContentAssetR\x06assets\"O\n" +
	"\x19CreateContentItemResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.overmindv.content.ContentItemR\x04item\"'\n" +
	"\x15GetContentItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16GetContentItemResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.overmindv.content.ContentItemR\x04item\"\x19\n" +
	"\x17ListContentItemsRequest\"P\n" +
	"\x18ListContentItemsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.overmindv.content.ContentItemR\x05items\"\xc1\x01\n" +
	"\x18UpdateContentItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\"O\n" +
	"\x19UpdateContentItemResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.overmindv.content.ContentItemR\x04item\"*\n" +
	"\x18DeleteContentItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x19DeleteContentItemResponse\x122\n" +
	"\x04item\x18\x01 \x01(\v2\x1e.overmindv.content.ContentItemR\x04item\"\xaf\x01\n" +
	"\x1cCreateContentRevisionRequest\x12&\n" +
	"\x0fcontent_item_id\x18\x01 \x01(\tR\rcontentItemId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"_\n" +
	"\x1dCreateContentRevisionResponse\x12>\n" +
	"\brevision\x18\x01 \x01(\v2\".overmindv.content.ContentRevisionR\brevision\"E\n" +
	"\x1bListContentRevisionsRequest\x12&\n" +
	"\x0fcontent_item_id\x18\x01 \x01(\tR\rcontentItemId\"`\n" +
	"\x1cListContentRevisionsResponse\x12@\n" +
	"\trevisions\x18\x01 \x03(\v2\".overmindv.content.ContentRevisionR\trevisions2\xa9\x06\n" +
	"\x0eContentService\x12n\n" +
	"\x11CreateContentItem\x12+.overmindv.content.CreateContentItemRequest\x1a,.overmindv.content.CreateContentItemResponse\x12e\n" +
	"\x0eGetContentItem\x12(.overmindv.content.GetContentItemRequest\x1a).overmindv.content.GetContentItemResponse\x12k\n" +
	"\x10ListContentItems\x12*.overmindv.content.ListContentItemsRequest\x1a+.overmindv.content.ListContentItemsResponse\x12n\n" +
	"\x11UpdateContentItem\x12+.overmindv.content.UpdateContentItemRequest\x1a,.overmindv.content.UpdateContentItemResponse\x12n\n" +
	"\x11DeleteContentItem\x12+.overmindv.content.DeleteContentItemRequest\x1a,.overmindv.content.DeleteContentItemResponse\x12z\n" +
	"\x15CreateContentRevision\x12/.overmindv.content.CreateContentRevisionRequest\x1a0.overmindv.content.CreateContentRevisionResponse\x12w\n" +
	"\x14ListContentRevisions\x12..overmindv.content.ListContentRevisionsRequest\x1a/.overmindv.content.ListContentRevisionsResponseB?Z=github.com/overmindv/content/internal/pkg/api/content;contentb\x06proto3"

var (
	file_api_content_content_proto_rawDescOnce sync.Once
	file_api_content_content_proto_rawDescData []byte
)

func file_api_content_content_proto_rawDescGZIP() []byte {
	file_api_content_content_proto_rawDescOnce.Do(func() {
		file_api_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)))
	})
	return file_api_content_content_proto_rawDescData
}

var file_api_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_content_content_proto_goTypes = []any{
	(*ContentItem)(nil),                   // 0: overmindv.content.ContentItem
	(*ContentRevision)(nil),               // 1: overmindv.content.ContentRevision
	(*Tag)(nil),                           // 2: overmindv.content.Tag
	(*ContentAsset)(nil),                  // 3: overmindv.content.ContentAsset
	(*CreateContentAsset)(nil),            // 4: overmindv.content.CreateContentAsset
	(*CreateContentItemRequest)(nil),      // 5: overmindv.content.CreateContentItemRequest
	(*CreateContentItemResponse)(nil),     // 6: overmindv.content.CreateContentItemResponse
	(*GetContentItemRequest)(nil),         // 7: overmindv.content.GetContentItemRequest
	(*GetContentItemResponse)(nil),        // 8: overmindv.content.GetContentItemResponse
	(*ListContentItemsRequest)(nil),       // 9: overmindv.content.ListContentItemsRequest
	(*ListContentItemsResponse)(nil),      // 10: overmindv.content.ListContentItemsResponse
	(*UpdateContentItemRequest)(nil),      // 11: overmindv.content.UpdateContentItemRequest
	(*UpdateContentItemResponse)(nil),     // 12: overmindv.content.UpdateContentItemResponse
	(*DeleteContentItemRequest)(nil),      // 13: overmindv.content.DeleteContentItemRequest
	(*DeleteContentItemResponse)(nil),     // 14: overmindv.content.DeleteContentItemResponse
	(*CreateContentRevisionRequest)(nil),  // 15: overmindv.content.CreateContentRevisionRequest
	(*CreateContentRevisionResponse)(nil), // 16: overmindv.content.CreateContentRevisionResponse
	(*ListContentRevisionsRequest)(nil),   // 17: overmindv.content.ListContentRevisionsRequest
	(*ListContentRevisionsResponse)(nil),  // 18: overmindv.content.ListContentRevisionsResponse
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_api_content_content_proto_depIdxs = []int32{
	19, // 0: overmindv.content.ContentItem.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: overmindv.content.ContentItem.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: overmindv.content.ContentItem.published_at:type_name -> google.protobuf.Timestamp
	19, // 3: overmindv.content.ContentItem.archived_at:type_name -> google.protobuf.Timestamp
	1,  // 4: overmindv.content.ContentItem.current_revision:type_name -> overmindv.content.ContentRevision
	2,  // 5: overmindv.content.ContentItem.tags:type_name -> overmindv.content.Tag
	3,  // 6: overmindv.content.ContentItem.assets:type_name -> overmindv.content.ContentAsset
	19, // 7: overmindv.content.ContentRevision.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: overmindv.content.Tag.created_at:type_name -> google.protobuf.Timestamp
	19, // 9: overmindv.content.ContentAsset.created_at:type_name -> google.protobuf.Timestamp
	4,  // 10: overmindv.content.CreateContentItemRequest.assets:type_name -> overmindv.content.CreateContentAsset
	0,  // 11: overmindv.content.CreateContentItemResponse.item:type_name -> overmindv.content.ContentItem
	0,  // 12: overmindv.content.GetContentItemResponse.item:type_name -> overmindv.content.ContentItem
	0,  // 13: overmindv.content.ListContentItemsResponse.items:type_name -> overmindv.content.ContentItem
	0,  // 14: overmindv.content.UpdateContentItemResponse.item:type_name -> overmindv.content.ContentItem
	0,  // 15: overmindv.content.DeleteContentItemResponse.item:type_name -> overmindv.content.ContentItem
	1,  // 16: overmindv.content.CreateContentRevisionResponse.revision:type_name -> overmindv.content.ContentRevision
	1,  // 17: overmindv.content.ListContentRevisionsResponse.revisions:type_name -> overmindv.content.ContentRevision
	5,  // 18: overmindv.content.ContentService.CreateContentItem:input_type -> overmindv.content.CreateContentItemRequest
	7,  // 19: overmindv.content.ContentService.GetContentItem:input_type -> overmindv.content.GetContentItemRequest
	9,  // 20: overmindv.content.ContentService.ListContentItems:input_type -> overmindv.content.ListContentItemsRequest
	11, // 21: overmindv.content.ContentService.UpdateContentItem:input_type -> overmindv.content.UpdateContentItemRequest
	13, // 22: overmindv.content.ContentService.DeleteContentItem:input_type -> overmindv.content.DeleteContentItemRequest
	15, // 23: overmindv.content.ContentService.CreateContentRevision:input_type -> overmindv.content.CreateContentRevisionRequest
	17, // 24: overmindv.content.ContentService.ListContentRevisions:input_type -> overmindv.content.ListContentRevisionsRequest
	6,  // 25: overmindv.content.ContentService.CreateContentItem:output_type -> overmindv.content.CreateContentItemResponse
	8,  // 26: overmindv.content.ContentService.GetContentItem:output_type -> overmindv.content.GetContentItemResponse
	10, // 27: overmindv.content.ContentService.ListContentItems:output_type -> overmindv.content.ListContentItemsResponse
	12, // 28: overmindv.content.ContentService.UpdateContentItem:output_type -> overmindv.content.UpdateContentItemResponse
	14, // 29: overmindv.content.ContentService.DeleteContentItem:output_type -> overmindv.content.DeleteContentItemResponse
	16, // 30: overmindv.content.ContentService.CreateContentRevision:output_type -> overmindv.content.CreateContentRevisionResponse
	18, // 31: overmindv.content.ContentService.ListContentRevisions:output_type -> overmindv.content.ListContentRevisionsResponse
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_content_content_proto_init() }
func file_api_content_content_proto_init() {
	if File_api_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_content_content_proto_rawDesc), len(file_api_content_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_content_content_proto_goTypes,
		DependencyIndexes: file_api_content_content_proto_depIdxs,
		MessageInfos:      file_api_content_content_proto_msgTypes,
	}.Build()
	File_api_content_content_proto = out.File
	file_api_content_content_proto_goTypes = nil
	file_api_content_content_proto_depIdxs = nil
}
