// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/content/content.proto

package content

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentService_CreateContentItem_FullMethodName     = "/overmindv.content.ContentService/CreateContentItem"
	ContentService_GetContentItem_FullMethodName        = "/overmindv.content.ContentService/GetContentItem"
	ContentService_ListContentItems_FullMethodName      = "/overmindv.content.ContentService/ListContentItems"
	ContentService_UpdateContentItem_FullMethodName     = "/overmindv.content.ContentService/UpdateContentItem"
	ContentService_DeleteContentItem_FullMethodName     = "/overmindv.content.ContentService/DeleteContentItem"
	ContentService_CreateContentRevision_FullMethodName = "/overmindv.content.ContentService/CreateContentRevision"
	ContentService_ListContentRevisions_FullMethodName  = "/overmindv.content.ContentService/ListContentRevisions"
)

// ContentServiceClient is the client API for ContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentServiceClient interface {
	CreateContentItem(ctx context.Context, in *CreateContentItemRequest, opts ...grpc.CallOption) (*CreateContentItemResponse, error)
	GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*GetContentItemResponse, error)
	ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error)
	UpdateContentItem(ctx context.Context, in *UpdateContentItemRequest, opts ...grpc.CallOption) (*UpdateContentItemResponse, error)
	DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error)
	CreateContentRevision(ctx context.Context, in *CreateContentRevisionRequest, opts ...grpc.CallOption) (*CreateContentRevisionResponse, error)
	ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error)
}

type contentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentServiceClient(cc grpc.ClientConnInterface) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) CreateContentItem(ctx context.Context, in *CreateContentItemRequest, opts ...grpc.CallOption) (*CreateContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentItemResponse)
	err := c.cc.Invoke(ctx, ContentService_CreateContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*GetContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentItemResponse)
	err := c.cc.Invoke(ctx, ContentService_GetContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentItemsResponse)
	err := c.cc.Invoke(ctx, ContentService_ListContentItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateContentItem(ctx context.Context, in *UpdateContentItemRequest, opts ...grpc.CallOption) (*UpdateContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContentItemResponse)
	err := c.cc.Invoke(ctx, ContentService_UpdateContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentItemResponse)
	err := c.cc.Invoke(ctx, ContentService_DeleteContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateContentRevision(ctx context.Context, in *CreateContentRevisionRequest, opts ...grpc.CallOption) (*CreateContentRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentRevisionResponse)
	err := c.cc.Invoke(ctx, ContentService_CreateContentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentRevisionsResponse)
	err := c.cc.Invoke(ctx, ContentService_ListContentRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServiceServer is the server API for ContentService service.
// All implementations must embed UnimplementedContentServiceServer
// for forward compatibility.
type ContentServiceServer interface {
	CreateContentItem(context.Context, *CreateContentItemRequest) (*CreateContentItemResponse, error)
	GetContentItem(context.Context, *GetContentItemRequest) (*GetContentItemResponse, error)
	ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error)
	UpdateContentItem(context.Context, *UpdateContentItemRequest) (*UpdateContentItemResponse, error)
	DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error)
	CreateContentRevision(context.Context, *CreateContentRevisionRequest) (*CreateContentRevisionResponse, error)
	ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error)
	mustEmbedUnimplementedContentServiceServer()
}

// UnimplementedContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServiceServer struct{}

func (UnimplementedContentServiceServer) CreateContentItem(context.Context, *CreateContentItemRequest) (*CreateContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContentItem not implemented")
}
func (UnimplementedContentServiceServer) GetContentItem(context.Context, *GetContentItemRequest) (*GetContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentItem not implemented")
}
func (UnimplementedContentServiceServer) ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentItems not implemented")
}
func (UnimplementedContentServiceServer) UpdateContentItem(context.Context, *UpdateContentItemRequest) (*UpdateContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContentItem not implemented")
}
func (UnimplementedContentServiceServer) DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContentItem not implemented")
}
func (UnimplementedContentServiceServer) CreateContentRevision(context.Context, *CreateContentRevisionRequest) (*CreateContentRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContentRevision not implemented")
}
func (UnimplementedContentServiceServer) ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentRevisions not implemented")
}
func (UnimplementedContentServiceServer) mustEmbedUnimplementedContentServiceServer() {}
func (UnimplementedContentServiceServer) testEmbeddedByValue()                        {}

// UnsafeContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServiceServer will
// result in compilation errors.
type UnsafeContentServiceServer interface {
	mustEmbedUnimplementedContentServiceServer()
}

func RegisterContentServiceServer(s grpc.ServiceRegistrar, srv ContentServiceServer) {
	// If the following call pancis, it indicates UnimplementedContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentService_ServiceDesc, srv)
}

func _ContentService_CreateContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_CreateContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateContentItem(ctx, req.(*CreateContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_GetContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContentItem(ctx, req.(*GetContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListContentItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListContentItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListContentItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListContentItems(ctx, req.(*ListContentItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_UpdateContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateContentItem(ctx, req.(*UpdateContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_DeleteContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).DeleteContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_DeleteContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).DeleteContentItem(ctx, req.(*DeleteContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateContentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateContentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_CreateContentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateContentRevision(ctx, req.(*CreateContentRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListContentRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListContentRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListContentRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListContentRevisions(ctx, req.(*ListContentRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentService_ServiceDesc is the grpc.ServiceDesc for ContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "overmindv.content.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContentItem",
			Handler:    _ContentService_CreateContentItem_Handler,
		},
		{
			MethodName: "GetContentItem",
			Handler:    _ContentService_GetContentItem_Handler,
		},
		{
			MethodName: "ListContentItems",
			Handler:    _ContentService_ListContentItems_Handler,
		},
		{
			MethodName: "UpdateContentItem",
			Handler:    _ContentService_UpdateContentItem_Handler,
		},
		{
			MethodName: "DeleteContentItem",
			Handler:    _ContentService_DeleteContentItem_Handler,
		},
		{
			MethodName: "CreateContentRevision",
			Handler:    _ContentService_CreateContentRevision_Handler,
		},
		{
			MethodName: "ListContentRevisions",
			Handler:    _ContentService_ListContentRevisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/content/content.proto",
}
