// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/bumblebee/bumblebee.proto

package bumblebee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BumblebeeService_CreateTemplateItem_FullMethodName = "/overmindv.bumblebee.BumblebeeService/CreateTemplateItem"
	BumblebeeService_GetTemplateItem_FullMethodName    = "/overmindv.bumblebee.BumblebeeService/GetTemplateItem"
	BumblebeeService_ListTemplateItems_FullMethodName  = "/overmindv.bumblebee.BumblebeeService/ListTemplateItems"
	BumblebeeService_UpdateTemplateItem_FullMethodName = "/overmindv.bumblebee.BumblebeeService/UpdateTemplateItem"
	BumblebeeService_DeleteTemplateItem_FullMethodName = "/overmindv.bumblebee.BumblebeeService/DeleteTemplateItem"
)

// BumblebeeServiceClient is the client API for BumblebeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BumblebeeServiceClient interface {
	CreateTemplateItem(ctx context.Context, in *CreateTemplateItemRequest, opts ...grpc.CallOption) (*CreateTemplateItemResponse, error)
	GetTemplateItem(ctx context.Context, in *GetTemplateItemRequest, opts ...grpc.CallOption) (*GetTemplateItemResponse, error)
	ListTemplateItems(ctx context.Context, in *ListTemplateItemsRequest, opts ...grpc.CallOption) (*ListTemplateItemsResponse, error)
	UpdateTemplateItem(ctx context.Context, in *UpdateTemplateItemRequest, opts ...grpc.CallOption) (*UpdateTemplateItemResponse, error)
	DeleteTemplateItem(ctx context.Context, in *DeleteTemplateItemRequest, opts ...grpc.CallOption) (*DeleteTemplateItemResponse, error)
}

type bumblebeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBumblebeeServiceClient(cc grpc.ClientConnInterface) BumblebeeServiceClient {
	return &bumblebeeServiceClient{cc}
}

func (c *bumblebeeServiceClient) CreateTemplateItem(ctx context.Context, in *CreateTemplateItemRequest, opts ...grpc.CallOption) (*CreateTemplateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_CreateTemplateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) GetTemplateItem(ctx context.Context, in *GetTemplateItemRequest, opts ...grpc.CallOption) (*GetTemplateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplateItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_GetTemplateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) ListTemplateItems(ctx context.Context, in *ListTemplateItemsRequest, opts ...grpc.CallOption) (*ListTemplateItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplateItemsResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_ListTemplateItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) UpdateTemplateItem(ctx context.Context, in *UpdateTemplateItemRequest, opts ...grpc.CallOption) (*UpdateTemplateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTemplateItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_UpdateTemplateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) DeleteTemplateItem(ctx context.Context, in *DeleteTemplateItemRequest, opts ...grpc.CallOption) (*DeleteTemplateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_DeleteTemplateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BumblebeeServiceServer is the server API for BumblebeeService service.
// All implementations must embed UnimplementedBumblebeeServiceServer
// for forward compatibility.
type BumblebeeServiceServer interface {
	CreateTemplateItem(context.Context, *CreateTemplateItemRequest) (*CreateTemplateItemResponse, error)
	GetTemplateItem(context.Context, *GetTemplateItemRequest) (*GetTemplateItemResponse, error)
	ListTemplateItems(context.Context, *ListTemplateItemsRequest) (*ListTemplateItemsResponse, error)
	UpdateTemplateItem(context.Context, *UpdateTemplateItemRequest) (*UpdateTemplateItemResponse, error)
	DeleteTemplateItem(context.Context, *DeleteTemplateItemRequest) (*DeleteTemplateItemResponse, error)
	mustEmbedUnimplementedBumblebeeServiceServer()
}

// UnimplementedBumblebeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBumblebeeServiceServer struct{}

func (UnimplementedBumblebeeServiceServer) CreateTemplateItem(context.Context, *CreateTemplateItemRequest) (*CreateTemplateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplateItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) GetTemplateItem(context.Context, *GetTemplateItemRequest) (*GetTemplateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplateItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) ListTemplateItems(context.Context, *ListTemplateItemsRequest) (*ListTemplateItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplateItems not implemented")
}
func (UnimplementedBumblebeeServiceServer) UpdateTemplateItem(context.Context, *UpdateTemplateItemRequest) (*UpdateTemplateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplateItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) DeleteTemplateItem(context.Context, *DeleteTemplateItemRequest) (*DeleteTemplateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplateItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) mustEmbedUnimplementedBumblebeeServiceServer() {}
func (UnimplementedBumblebeeServiceServer) testEmbeddedByValue()                          {}

// UnsafeBumblebeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BumblebeeServiceServer will
// result in compilation errors.
type UnsafeBumblebeeServiceServer interface {
	mustEmbedUnimplementedBumblebeeServiceServer()
}

func RegisterBumblebeeServiceServer(s grpc.ServiceRegistrar, srv BumblebeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedBumblebeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BumblebeeService_ServiceDesc, srv)
}

func _BumblebeeService_CreateTemplateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).CreateTemplateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_CreateTemplateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).CreateTemplateItem(ctx, req.(*CreateTemplateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_GetTemplateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).GetTemplateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_GetTemplateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).GetTemplateItem(ctx, req.(*GetTemplateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_ListTemplateItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplateItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).ListTemplateItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_ListTemplateItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).ListTemplateItems(ctx, req.(*ListTemplateItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_UpdateTemplateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).UpdateTemplateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_UpdateTemplateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).UpdateTemplateItem(ctx, req.(*UpdateTemplateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_DeleteTemplateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).DeleteTemplateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_DeleteTemplateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).DeleteTemplateItem(ctx, req.(*DeleteTemplateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BumblebeeService_ServiceDesc is the grpc.ServiceDesc for BumblebeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BumblebeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "overmindv.bumblebee.BumblebeeService",
	HandlerType: (*BumblebeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplateItem",
			Handler:    _BumblebeeService_CreateTemplateItem_Handler,
		},
		{
			MethodName: "GetTemplateItem",
			Handler:    _BumblebeeService_GetTemplateItem_Handler,
		},
		{
			MethodName: "ListTemplateItems",
			Handler:    _BumblebeeService_ListTemplateItems_Handler,
		},
		{
			MethodName: "UpdateTemplateItem",
			Handler:    _BumblebeeService_UpdateTemplateItem_Handler,
		},
		{
			MethodName: "DeleteTemplateItem",
			Handler:    _BumblebeeService_DeleteTemplateItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bumblebee/bumblebee.proto",
}
