// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/bumblebee/bumblebee.proto

package bumblebee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BumblebeeService_CreateContentItem_FullMethodName     = "/overmindv.bumblebee.BumblebeeService/CreateContentItem"
	BumblebeeService_GetContentItem_FullMethodName        = "/overmindv.bumblebee.BumblebeeService/GetContentItem"
	BumblebeeService_ListContentItems_FullMethodName      = "/overmindv.bumblebee.BumblebeeService/ListContentItems"
	BumblebeeService_UpdateContentItem_FullMethodName     = "/overmindv.bumblebee.BumblebeeService/UpdateContentItem"
	BumblebeeService_DeleteContentItem_FullMethodName     = "/overmindv.bumblebee.BumblebeeService/DeleteContentItem"
	BumblebeeService_CreateContentRevision_FullMethodName = "/overmindv.bumblebee.BumblebeeService/CreateContentRevision"
	BumblebeeService_ListContentRevisions_FullMethodName  = "/overmindv.bumblebee.BumblebeeService/ListContentRevisions"
)

// BumblebeeServiceClient is the client API for BumblebeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BumblebeeServiceClient interface {
	CreateContentItem(ctx context.Context, in *CreateContentItemRequest, opts ...grpc.CallOption) (*CreateContentItemResponse, error)
	GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*GetContentItemResponse, error)
	ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error)
	UpdateContentItem(ctx context.Context, in *UpdateContentItemRequest, opts ...grpc.CallOption) (*UpdateContentItemResponse, error)
	DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error)
	CreateContentRevision(ctx context.Context, in *CreateContentRevisionRequest, opts ...grpc.CallOption) (*CreateContentRevisionResponse, error)
	ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error)
}

type bumblebeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBumblebeeServiceClient(cc grpc.ClientConnInterface) BumblebeeServiceClient {
	return &bumblebeeServiceClient{cc}
}

func (c *bumblebeeServiceClient) CreateContentItem(ctx context.Context, in *CreateContentItemRequest, opts ...grpc.CallOption) (*CreateContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_CreateContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*GetContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_GetContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentItemsResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_ListContentItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) UpdateContentItem(ctx context.Context, in *UpdateContentItemRequest, opts ...grpc.CallOption) (*UpdateContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContentItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_UpdateContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentItemResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_DeleteContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) CreateContentRevision(ctx context.Context, in *CreateContentRevisionRequest, opts ...grpc.CallOption) (*CreateContentRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentRevisionResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_CreateContentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bumblebeeServiceClient) ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentRevisionsResponse)
	err := c.cc.Invoke(ctx, BumblebeeService_ListContentRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BumblebeeServiceServer is the server API for BumblebeeService service.
// All implementations must embed UnimplementedBumblebeeServiceServer
// for forward compatibility.
type BumblebeeServiceServer interface {
	CreateContentItem(context.Context, *CreateContentItemRequest) (*CreateContentItemResponse, error)
	GetContentItem(context.Context, *GetContentItemRequest) (*GetContentItemResponse, error)
	ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error)
	UpdateContentItem(context.Context, *UpdateContentItemRequest) (*UpdateContentItemResponse, error)
	DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error)
	CreateContentRevision(context.Context, *CreateContentRevisionRequest) (*CreateContentRevisionResponse, error)
	ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error)
	mustEmbedUnimplementedBumblebeeServiceServer()
}

// UnimplementedBumblebeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBumblebeeServiceServer struct{}

func (UnimplementedBumblebeeServiceServer) CreateContentItem(context.Context, *CreateContentItemRequest) (*CreateContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContentItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) GetContentItem(context.Context, *GetContentItemRequest) (*GetContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentItems not implemented")
}
func (UnimplementedBumblebeeServiceServer) UpdateContentItem(context.Context, *UpdateContentItemRequest) (*UpdateContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContentItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContentItem not implemented")
}
func (UnimplementedBumblebeeServiceServer) CreateContentRevision(context.Context, *CreateContentRevisionRequest) (*CreateContentRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContentRevision not implemented")
}
func (UnimplementedBumblebeeServiceServer) ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentRevisions not implemented")
}
func (UnimplementedBumblebeeServiceServer) mustEmbedUnimplementedBumblebeeServiceServer() {}
func (UnimplementedBumblebeeServiceServer) testEmbeddedByValue()                          {}

// UnsafeBumblebeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BumblebeeServiceServer will
// result in compilation errors.
type UnsafeBumblebeeServiceServer interface {
	mustEmbedUnimplementedBumblebeeServiceServer()
}

func RegisterBumblebeeServiceServer(s grpc.ServiceRegistrar, srv BumblebeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedBumblebeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BumblebeeService_ServiceDesc, srv)
}

func _BumblebeeService_CreateContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).CreateContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_CreateContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).CreateContentItem(ctx, req.(*CreateContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_GetContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).GetContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_GetContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).GetContentItem(ctx, req.(*GetContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_ListContentItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).ListContentItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_ListContentItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).ListContentItems(ctx, req.(*ListContentItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_UpdateContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).UpdateContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_UpdateContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).UpdateContentItem(ctx, req.(*UpdateContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_DeleteContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).DeleteContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_DeleteContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).DeleteContentItem(ctx, req.(*DeleteContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_CreateContentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).CreateContentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_CreateContentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).CreateContentRevision(ctx, req.(*CreateContentRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BumblebeeService_ListContentRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BumblebeeServiceServer).ListContentRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BumblebeeService_ListContentRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BumblebeeServiceServer).ListContentRevisions(ctx, req.(*ListContentRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BumblebeeService_ServiceDesc is the grpc.ServiceDesc for BumblebeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BumblebeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "overmindv.bumblebee.BumblebeeService",
	HandlerType: (*BumblebeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContentItem",
			Handler:    _BumblebeeService_CreateContentItem_Handler,
		},
		{
			MethodName: "GetContentItem",
			Handler:    _BumblebeeService_GetContentItem_Handler,
		},
		{
			MethodName: "ListContentItems",
			Handler:    _BumblebeeService_ListContentItems_Handler,
		},
		{
			MethodName: "UpdateContentItem",
			Handler:    _BumblebeeService_UpdateContentItem_Handler,
		},
		{
			MethodName: "DeleteContentItem",
			Handler:    _BumblebeeService_DeleteContentItem_Handler,
		},
		{
			MethodName: "CreateContentRevision",
			Handler:    _BumblebeeService_CreateContentRevision_Handler,
		},
		{
			MethodName: "ListContentRevisions",
			Handler:    _BumblebeeService_ListContentRevisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bumblebee/bumblebee.proto",
}
