// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: api/bumblebee/bumblebee.proto

package bumblebee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateItem) Reset() {
	*x = TemplateItem{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateItem) ProtoMessage() {}

func (x *TemplateItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateItem.ProtoReflect.Descriptor instead.
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TemplateItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TemplateItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TemplateItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTemplateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateItemRequest) Reset() {
	*x = CreateTemplateItemRequest{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateItemRequest) ProtoMessage() {}

func (x *CreateTemplateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTemplateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTemplateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TemplateItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateItemResponse) Reset() {
	*x = CreateTemplateItemResponse{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateItemResponse) ProtoMessage() {}

func (x *CreateTemplateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTemplateItemResponse) GetItem() *TemplateItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetTemplateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateItemRequest) Reset() {
	*x = GetTemplateItemRequest{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateItemRequest) ProtoMessage() {}

func (x *GetTemplateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateItemRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemplateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTemplateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TemplateItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateItemResponse) Reset() {
	*x = GetTemplateItemResponse{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateItemResponse) ProtoMessage() {}

func (x *GetTemplateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateItemResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{4}
}

func (x *GetTemplateItemResponse) GetItem() *TemplateItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListTemplateItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateItemsRequest) Reset() {
	*x = ListTemplateItemsRequest{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateItemsRequest) ProtoMessage() {}

func (x *ListTemplateItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateItemsRequest.ProtoReflect.Descriptor instead.
func (*ListTemplateItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{5}
}

type ListTemplateItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TemplateItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateItemsResponse) Reset() {
	*x = ListTemplateItemsResponse{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateItemsResponse) ProtoMessage() {}

func (x *ListTemplateItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateItemsResponse.ProtoReflect.Descriptor instead.
func (*ListTemplateItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{6}
}

func (x *ListTemplateItemsResponse) GetItems() []*TemplateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateTemplateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateItemRequest) Reset() {
	*x = UpdateTemplateItemRequest{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateItemRequest) ProtoMessage() {}

func (x *UpdateTemplateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTemplateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TemplateItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateItemResponse) Reset() {
	*x = UpdateTemplateItemResponse{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateItemResponse) ProtoMessage() {}

func (x *UpdateTemplateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTemplateItemResponse) GetItem() *TemplateItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteTemplateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateItemRequest) Reset() {
	*x = DeleteTemplateItemRequest{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateItemRequest) ProtoMessage() {}

func (x *DeleteTemplateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTemplateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTemplateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TemplateItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateItemResponse) Reset() {
	*x = DeleteTemplateItemResponse{}
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateItemResponse) ProtoMessage() {}

func (x *DeleteTemplateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bumblebee_bumblebee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateItemResponse) Descriptor() ([]byte, []int) {
	return file_api_bumblebee_bumblebee_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTemplateItemResponse) GetItem() *TemplateItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_api_bumblebee_bumblebee_proto protoreflect.FileDescriptor

const file_api_bumblebee_bumblebee_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/bumblebee/bumblebee.proto\x12\x13overmindv.bumblebee\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\fTemplateItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"i\n" +
	"\x19CreateTemplateItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"S\n" +
	"\x1aCreateTemplateItemResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.overmindv.bumblebee.TemplateItemR\x04item\"(\n" +
	"\x16GetTemplateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x17GetTemplateItemResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.overmindv.bumblebee.TemplateItemR\x04item\"\x1a\n" +
	"\x18ListTemplateItemsRequest\"T\n" +
	"\x19ListTemplateItemsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.overmindv.bumblebee.TemplateItemR\x05items\"y\n" +
	"\x19UpdateTemplateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"S\n" +
	"\x1aUpdateTemplateItemResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.overmindv.bumblebee.TemplateItemR\x04item\"+\n" +
	"\x19DeleteTemplateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1aDeleteTemplateItemResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.overmindv.bumblebee.TemplateItemR\x04item2\xd9\x04\n" +
	"\x10BumblebeeService\x12u\n" +
	"\x12CreateTemplateItem\x12..overmindv.bumblebee.CreateTemplateItemRequest\x1a/.overmindv.bumblebee.CreateTemplateItemResponse\x12l\n" +
	"\x0fGetTemplateItem\x12+.overmindv.bumblebee.GetTemplateItemRequest\x1a,.overmindv.bumblebee.GetTemplateItemResponse\x12r\n" +
	"\x11ListTemplateItems\x12-.overmindv.bumblebee.ListTemplateItemsRequest\x1a..overmindv.bumblebee.ListTemplateItemsResponse\x12u\n" +
	"\x12UpdateTemplateItem\x12..overmindv.bumblebee.UpdateTemplateItemRequest\x1a/.overmindv.bumblebee.UpdateTemplateItemResponse\x12u\n" +
	"\x12DeleteTemplateItem\x12..overmindv.bumblebee.DeleteTemplateItemRequest\x1a/.overmindv.bumblebee.DeleteTemplateItemResponseBEZCgithub.com/overmindv/bumblebee/internal/pkg/api/bumblebee;bumblebeeb\x06proto3"

var (
	file_api_bumblebee_bumblebee_proto_rawDescOnce sync.Once
	file_api_bumblebee_bumblebee_proto_rawDescData []byte
)

func file_api_bumblebee_bumblebee_proto_rawDescGZIP() []byte {
	file_api_bumblebee_bumblebee_proto_rawDescOnce.Do(func() {
		file_api_bumblebee_bumblebee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bumblebee_bumblebee_proto_rawDesc), len(file_api_bumblebee_bumblebee_proto_rawDesc)))
	})
	return file_api_bumblebee_bumblebee_proto_rawDescData
}

var file_api_bumblebee_bumblebee_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_bumblebee_bumblebee_proto_goTypes = []any{
	(*TemplateItem)(nil),               // 0: overmindv.bumblebee.TemplateItem
	(*CreateTemplateItemRequest)(nil),  // 1: overmindv.bumblebee.CreateTemplateItemRequest
	(*CreateTemplateItemResponse)(nil), // 2: overmindv.bumblebee.CreateTemplateItemResponse
	(*GetTemplateItemRequest)(nil),     // 3: overmindv.bumblebee.GetTemplateItemRequest
	(*GetTemplateItemResponse)(nil),    // 4: overmindv.bumblebee.GetTemplateItemResponse
	(*ListTemplateItemsRequest)(nil),   // 5: overmindv.bumblebee.ListTemplateItemsRequest
	(*ListTemplateItemsResponse)(nil),  // 6: overmindv.bumblebee.ListTemplateItemsResponse
	(*UpdateTemplateItemRequest)(nil),  // 7: overmindv.bumblebee.UpdateTemplateItemRequest
	(*UpdateTemplateItemResponse)(nil), // 8: overmindv.bumblebee.UpdateTemplateItemResponse
	(*DeleteTemplateItemRequest)(nil),  // 9: overmindv.bumblebee.DeleteTemplateItemRequest
	(*DeleteTemplateItemResponse)(nil), // 10: overmindv.bumblebee.DeleteTemplateItemResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_api_bumblebee_bumblebee_proto_depIdxs = []int32{
	11, // 0: overmindv.bumblebee.TemplateItem.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: overmindv.bumblebee.TemplateItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: overmindv.bumblebee.CreateTemplateItemResponse.item:type_name -> overmindv.bumblebee.TemplateItem
	0,  // 3: overmindv.bumblebee.GetTemplateItemResponse.item:type_name -> overmindv.bumblebee.TemplateItem
	0,  // 4: overmindv.bumblebee.ListTemplateItemsResponse.items:type_name -> overmindv.bumblebee.TemplateItem
	0,  // 5: overmindv.bumblebee.UpdateTemplateItemResponse.item:type_name -> overmindv.bumblebee.TemplateItem
	0,  // 6: overmindv.bumblebee.DeleteTemplateItemResponse.item:type_name -> overmindv.bumblebee.TemplateItem
	1,  // 7: overmindv.bumblebee.BumblebeeService.CreateTemplateItem:input_type -> overmindv.bumblebee.CreateTemplateItemRequest
	3,  // 8: overmindv.bumblebee.BumblebeeService.GetTemplateItem:input_type -> overmindv.bumblebee.GetTemplateItemRequest
	5,  // 9: overmindv.bumblebee.BumblebeeService.ListTemplateItems:input_type -> overmindv.bumblebee.ListTemplateItemsRequest
	7,  // 10: overmindv.bumblebee.BumblebeeService.UpdateTemplateItem:input_type -> overmindv.bumblebee.UpdateTemplateItemRequest
	9,  // 11: overmindv.bumblebee.BumblebeeService.DeleteTemplateItem:input_type -> overmindv.bumblebee.DeleteTemplateItemRequest
	2,  // 12: overmindv.bumblebee.BumblebeeService.CreateTemplateItem:output_type -> overmindv.bumblebee.CreateTemplateItemResponse
	4,  // 13: overmindv.bumblebee.BumblebeeService.GetTemplateItem:output_type -> overmindv.bumblebee.GetTemplateItemResponse
	6,  // 14: overmindv.bumblebee.BumblebeeService.ListTemplateItems:output_type -> overmindv.bumblebee.ListTemplateItemsResponse
	8,  // 15: overmindv.bumblebee.BumblebeeService.UpdateTemplateItem:output_type -> overmindv.bumblebee.UpdateTemplateItemResponse
	10, // 16: overmindv.bumblebee.BumblebeeService.DeleteTemplateItem:output_type -> overmindv.bumblebee.DeleteTemplateItemResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_bumblebee_bumblebee_proto_init() }
func file_api_bumblebee_bumblebee_proto_init() {
	if File_api_bumblebee_bumblebee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bumblebee_bumblebee_proto_rawDesc), len(file_api_bumblebee_bumblebee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bumblebee_bumblebee_proto_goTypes,
		DependencyIndexes: file_api_bumblebee_bumblebee_proto_depIdxs,
		MessageInfos:      file_api_bumblebee_bumblebee_proto_msgTypes,
	}.Build()
	File_api_bumblebee_bumblebee_proto = out.File
	file_api_bumblebee_bumblebee_proto_goTypes = nil
	file_api_bumblebee_bumblebee_proto_depIdxs = nil
}
