// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/service/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/service/contracts.go -destination=internal/mock/content_item_dependencies.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/overmindv/content/internal/pkg/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockContentItemStore is a mock of ContentItemStore interface.
type MockContentItemStore struct {
	ctrl     *gomock.Controller
	recorder *MockContentItemStoreMockRecorder
	isgomock struct{}
}

// MockContentItemStoreMockRecorder is the mock recorder for MockContentItemStore.
type MockContentItemStoreMockRecorder struct {
	mock *MockContentItemStore
}

// NewMockContentItemStore creates a new mock instance.
func NewMockContentItemStore(ctrl *gomock.Controller) *MockContentItemStore {
	mock := &MockContentItemStore{ctrl: ctrl}
	mock.recorder = &MockContentItemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentItemStore) EXPECT() *MockContentItemStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContentItemStore) Create(ctx context.Context, input domain.CreateContentItemInput) (domain.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(domain.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContentItemStoreMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContentItemStore)(nil).Create), ctx, input)
}

// CreateRevision mocks base method.
func (m *MockContentItemStore) CreateRevision(ctx context.Context, input domain.CreateContentRevisionInput) (domain.ContentRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevision", ctx, input)
	ret0, _ := ret[0].(domain.ContentRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRevision indicates an expected call of CreateRevision.
func (mr *MockContentItemStoreMockRecorder) CreateRevision(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevision", reflect.TypeOf((*MockContentItemStore)(nil).CreateRevision), ctx, input)
}

// Delete mocks base method.
func (m *MockContentItemStore) Delete(ctx context.Context, id string) (domain.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(domain.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockContentItemStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContentItemStore)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockContentItemStore) Get(ctx context.Context, id string) (domain.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContentItemStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContentItemStore)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockContentItemStore) List(ctx context.Context) ([]domain.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockContentItemStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContentItemStore)(nil).List), ctx)
}

// ListRevisions mocks base method.
func (m *MockContentItemStore) ListRevisions(ctx context.Context, contentItemID string) ([]domain.ContentRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevisions", ctx, contentItemID)
	ret0, _ := ret[0].([]domain.ContentRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevisions indicates an expected call of ListRevisions.
func (mr *MockContentItemStoreMockRecorder) ListRevisions(ctx, contentItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevisions", reflect.TypeOf((*MockContentItemStore)(nil).ListRevisions), ctx, contentItemID)
}

// PingContext mocks base method.
func (m *MockContentItemStore) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockContentItemStoreMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockContentItemStore)(nil).PingContext), ctx)
}

// Update mocks base method.
func (m *MockContentItemStore) Update(ctx context.Context, input domain.UpdateContentItemInput) (domain.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(domain.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockContentItemStoreMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContentItemStore)(nil).Update), ctx, input)
}

// MockContentItemEventPublisher is a mock of ContentItemEventPublisher interface.
type MockContentItemEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockContentItemEventPublisherMockRecorder
	isgomock struct{}
}

// MockContentItemEventPublisherMockRecorder is the mock recorder for MockContentItemEventPublisher.
type MockContentItemEventPublisherMockRecorder struct {
	mock *MockContentItemEventPublisher
}

// NewMockContentItemEventPublisher creates a new mock instance.
func NewMockContentItemEventPublisher(ctrl *gomock.Controller) *MockContentItemEventPublisher {
	mock := &MockContentItemEventPublisher{ctrl: ctrl}
	mock.recorder = &MockContentItemEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentItemEventPublisher) EXPECT() *MockContentItemEventPublisherMockRecorder {
	return m.recorder
}

// PublishCreated mocks base method.
func (m *MockContentItemEventPublisher) PublishCreated(ctx context.Context, item domain.ContentItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishCreated", ctx, item)
}

// PublishCreated indicates an expected call of PublishCreated.
func (mr *MockContentItemEventPublisherMockRecorder) PublishCreated(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCreated", reflect.TypeOf((*MockContentItemEventPublisher)(nil).PublishCreated), ctx, item)
}

// PublishDeleted mocks base method.
func (m *MockContentItemEventPublisher) PublishDeleted(ctx context.Context, item domain.ContentItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishDeleted", ctx, item)
}

// PublishDeleted indicates an expected call of PublishDeleted.
func (mr *MockContentItemEventPublisherMockRecorder) PublishDeleted(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeleted", reflect.TypeOf((*MockContentItemEventPublisher)(nil).PublishDeleted), ctx, item)
}

// PublishRevisionCreated mocks base method.
func (m *MockContentItemEventPublisher) PublishRevisionCreated(ctx context.Context, revision domain.ContentRevision) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishRevisionCreated", ctx, revision)
}

// PublishRevisionCreated indicates an expected call of PublishRevisionCreated.
func (mr *MockContentItemEventPublisherMockRecorder) PublishRevisionCreated(ctx, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRevisionCreated", reflect.TypeOf((*MockContentItemEventPublisher)(nil).PublishRevisionCreated), ctx, revision)
}

// PublishUpdated mocks base method.
func (m *MockContentItemEventPublisher) PublishUpdated(ctx context.Context, item domain.ContentItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishUpdated", ctx, item)
}

// PublishUpdated indicates an expected call of PublishUpdated.
func (mr *MockContentItemEventPublisherMockRecorder) PublishUpdated(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUpdated", reflect.TypeOf((*MockContentItemEventPublisher)(nil).PublishUpdated), ctx, item)
}
