// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/service/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/service/contracts.go -destination=internal/mock/template_item_dependencies.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/overmindv/bumblebee/internal/pkg/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateItemStore is a mock of TemplateItemStore interface.
type MockTemplateItemStore struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateItemStoreMockRecorder
	isgomock struct{}
}

// MockTemplateItemStoreMockRecorder is the mock recorder for MockTemplateItemStore.
type MockTemplateItemStoreMockRecorder struct {
	mock *MockTemplateItemStore
}

// NewMockTemplateItemStore creates a new mock instance.
func NewMockTemplateItemStore(ctrl *gomock.Controller) *MockTemplateItemStore {
	mock := &MockTemplateItemStore{ctrl: ctrl}
	mock.recorder = &MockTemplateItemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateItemStore) EXPECT() *MockTemplateItemStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplateItemStore) Create(ctx context.Context, input domain.CreateTemplateItemInput) (domain.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(domain.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTemplateItemStoreMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplateItemStore)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockTemplateItemStore) Delete(ctx context.Context, id string) (domain.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(domain.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTemplateItemStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplateItemStore)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTemplateItemStore) Get(ctx context.Context, id string) (domain.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTemplateItemStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTemplateItemStore)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTemplateItemStore) List(ctx context.Context) ([]domain.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTemplateItemStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTemplateItemStore)(nil).List), ctx)
}

// PingContext mocks base method.
func (m *MockTemplateItemStore) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockTemplateItemStoreMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockTemplateItemStore)(nil).PingContext), ctx)
}

// Update mocks base method.
func (m *MockTemplateItemStore) Update(ctx context.Context, input domain.UpdateTemplateItemInput) (domain.TemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(domain.TemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTemplateItemStoreMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTemplateItemStore)(nil).Update), ctx, input)
}

// MockTemplateItemEventPublisher is a mock of TemplateItemEventPublisher interface.
type MockTemplateItemEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateItemEventPublisherMockRecorder
	isgomock struct{}
}

// MockTemplateItemEventPublisherMockRecorder is the mock recorder for MockTemplateItemEventPublisher.
type MockTemplateItemEventPublisherMockRecorder struct {
	mock *MockTemplateItemEventPublisher
}

// NewMockTemplateItemEventPublisher creates a new mock instance.
func NewMockTemplateItemEventPublisher(ctrl *gomock.Controller) *MockTemplateItemEventPublisher {
	mock := &MockTemplateItemEventPublisher{ctrl: ctrl}
	mock.recorder = &MockTemplateItemEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateItemEventPublisher) EXPECT() *MockTemplateItemEventPublisherMockRecorder {
	return m.recorder
}

// PublishCreated mocks base method.
func (m *MockTemplateItemEventPublisher) PublishCreated(ctx context.Context, item domain.TemplateItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishCreated", ctx, item)
}

// PublishCreated indicates an expected call of PublishCreated.
func (mr *MockTemplateItemEventPublisherMockRecorder) PublishCreated(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCreated", reflect.TypeOf((*MockTemplateItemEventPublisher)(nil).PublishCreated), ctx, item)
}

// PublishDeleted mocks base method.
func (m *MockTemplateItemEventPublisher) PublishDeleted(ctx context.Context, item domain.TemplateItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishDeleted", ctx, item)
}

// PublishDeleted indicates an expected call of PublishDeleted.
func (mr *MockTemplateItemEventPublisherMockRecorder) PublishDeleted(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeleted", reflect.TypeOf((*MockTemplateItemEventPublisher)(nil).PublishDeleted), ctx, item)
}

// PublishUpdated mocks base method.
func (m *MockTemplateItemEventPublisher) PublishUpdated(ctx context.Context, item domain.TemplateItem) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishUpdated", ctx, item)
}

// PublishUpdated indicates an expected call of PublishUpdated.
func (mr *MockTemplateItemEventPublisherMockRecorder) PublishUpdated(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUpdated", reflect.TypeOf((*MockTemplateItemEventPublisher)(nil).PublishUpdated), ctx, item)
}
